export const site = {
  name: 'Antonio Augusto Firmo Correa',
  wordmark: 'Antonio Augusto',
  domain: 'https://antonioworks.vercel.app',
  resumeUrl: '/curriculo-antonio.pdf',
  location: 'Caçador, SC',
  year: 2026,
  description: 'Assistente de Projetos e estudante de Análise e Desenvolvimento de Sistemas em transição para tecnologia.',
  banner: '/banner.gif',
  portraits: ['/antonio-profile-upscaled.png'],
  githubUser: 'anttonioagst',
  roles: ['Assistente de Projetos', 'Estudante de ADS', 'Automação com IA'],
  availability: 'Buscando primeira oportunidade em tecnologia',
  about: [
    'Atuei em projetos de <b>arquitetura e engenharia</b>, usando diariamente ferramentas como AutoCAD, Revit e 3ds Max.',
    'O contato direto com esses softwares despertou meu interesse por <b>desenvolvimento de aplicações</b> e me levou a estudar tecnologia.',
    'Hoje curso <b>Análise e Desenvolvimento de Sistemas</b>. Estudo a área há cerca de um ano e meio e busco minha primeira oportunidade em tecnologia.',
  ],
  links: [
    { label: 'E-mail', href: 'mailto:anttonioaugustofc@gmail.com', icon: 'mail' },
    { label: 'GitHub', href: 'https://github.com/anttonioagst', icon: 'github' },
    { label: 'LinkedIn', href: 'https://www.linkedin.com/in/anttonioagst/', icon: 'linkedin' },
    { label: 'Instagram', href: 'https://www.instagram.com/anttonioaugusto_/', icon: 'instagram' },
    { label: 'Currículo', href: '/curriculo-antonio.pdf', icon: 'resume' },
  ],
  projects: [
    { title: 'DevLinks', subtitle: 'Seus links em um só lugar.', description: 'Um cartão de visitas digital para reunir projetos, contatos e redes em uma interface simples e direta.', detail: 'Um agregador de links pessoais que reúne projetos, redes sociais e formas de contato em uma página simples, usada como cartão de visitas digital.', stack: ['HTML', 'CSS', 'JavaScript', 'Figma'], ai: 'Claude Code e Cursor', tags: ['HTML', 'CSS', 'JavaScript'], image: '/projects/dev-links.jpg', url: 'https://anttonioagst.github.io/dev-links/', repo: 'https://github.com/anttonioagst/dev-links' },
    { title: 'Wiip Club', subtitle: 'Comunidades para construir em público.', description: 'Espaço para descobrir comunidades, acompanhar projetos reais e compartilhar a jornada de criação.', detail: 'Uma comunidade voltada a quem constrói em público. A página apresenta a proposta, os projetos compartilhados e a identidade visual do Wiip Club.', stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS'], ai: 'Claude Code e Cursor', tags: ['Comunidade', 'Design', 'UI'], image: '/projects/wiip-hero.jpg', url: 'https://wiip.club/', repo: 'https://github.com/anttonioagst/wiipclub' },
    { title: 'Buddies', subtitle: 'Pack de agentes e fluxos de IA.', description: 'Landing page para apresentar bundles de IA e fluxos de trabalho vendidos na Whop.', detail: 'Uma vitrine para bundles de agentes, bots e fluxos de trabalho. Apresenta a oferta e direciona a compra pela Whop.', stack: ['Vite', 'React', 'TypeScript', 'Tailwind CSS', 'GSAP', 'Whop'], ai: 'Claude Code e Cursor', tags: ['TypeScript', 'Whop', 'Workflows'], image: '/projects/buddies-live-hero.png', url: 'https://crevos.whop.site/', repo: 'https://github.com/anttonioagst/buddies' },
  ],
  stack: [
    ['HTML','frontend','https://developer.mozilla.org/pt-BR/docs/Web/HTML',261.63],
    ['CSS','frontend','https://developer.mozilla.org/pt-BR/docs/Web/CSS',293.66],
    ['JavaScript','frontend','https://developer.mozilla.org/pt-BR/docs/Web/JavaScript',329.63],
    ['Git','tools','https://git-scm.com/',349.23],
    ['GitHub','tools','https://github.com/',369.99],
    ['VS Code','tools','https://code.visualstudio.com/',392],
    ['Cursor','tools','https://cursor.com/',440],
    ['Codex','tools','https://openai.com/codex/',523.25],
    ['Claude','tools','https://claude.ai/',587.33],
  ] as [string,string,string,number][],
  highlights: [] as {name:string;handle:string;text:string;avatar:string;url:string;pinned?:boolean}[],
  experience: [
    {
      company: 'Grupo Estel',
      role: 'Assistente de Projetos I',
      period: '2026–atual',
      description: 'Relatórios topográficos e apoio à Qualidade com AutoCAD e Excel.',
      logo: '/companies/estel-premium.png',
      caseHref: '/projects/painel-de-qualidade',
      tools: [
        { name: 'Claude', color: '#d97757' },
      ],
      story: [
        'Nesse período montei um painel de controles da Qualidade em Google Apps Script, com o Google Drive como banco. As telas reúnem consultas técnicas, relatórios de topografia, equipamentos e checklist de montagem.',
        'Foi a primeira vez que apliquei IA em um trabalho real.',
        'Os gerentes da Estel viram o uso no escritório e me incentivaram a montar um BIS, o programa da empresa que dá prêmios e oportunidades a quem cria coisa nova.',
        'Além do controle interno, o painel também serve em campo e liga a obra ao escritório.',
      ],
      shots: [
        { src: '/experience/estel/consultas-tecnicas.png', alt: 'Tela de Consultas Técnicas do painel da Qualidade da Estel', caption: 'Consultas Técnicas' },
        { src: '/experience/estel/relatorios-topografia.png', alt: 'Tela de Relatórios de Topografia do painel da Qualidade da Estel', caption: 'Relatórios de Topografia' },
        { src: '/experience/estel/equipamentos.png', alt: 'Tela de Equipamentos do painel da Qualidade da Estel', caption: 'Equipamentos' },
        { src: '/experience/estel/checklist-montagem.png', alt: 'Tela de Checklist de Montagem do painel da Qualidade da Estel', caption: 'Checklist de Montagem' },
      ],
    },
    { company: 'Complementary Projetos', role: 'Projetista', period: '2022–2025', description: 'Projetos arquitetônicos e de engenharia em BIM com Revit e AutoCAD.', logo: '/companies/complementary-icon.png' },
    { company: 'Blackbox', role: 'Modelagem 3D para arquitetura', period: '2021', description: 'Produção de modelos com 3ds Max e AutoCAD.', logo: '/companies/blackbox.svg' },
    { company: 'Construtora Pasqualotto', role: 'Jovem Aprendiz — Engenharia', period: '2020', description: 'Início profissional na área de engenharia.', logo: '/companies/pasqualotto-premium.png' },
  ],
  qualityPanel: {
    href: '/projects/painel-de-qualidade',
    title: 'Painel de Qualidade',
    eyebrow: 'Case · Grupo Estel · 2026',
    summary: 'Um aplicativo interno que reúne os controles da Qualidade em um só lugar, para a obra e o escritório consultarem a mesma informação.',
    facts: [
      { label: 'Em uso', value: 'Desde julho de 2026' },
      { label: 'Quem usa', value: 'Obra Adami, Planejamento e Qualidade' },
      { label: 'Base', value: 'Google Apps Script e Google Drive' },
      { label: 'Construção', value: 'Ideia minha, código feito com IA' },
    ],
    problem: [
      'Os controles da Qualidade viviam em planilhas e no LMS. A mesma informação aparecia em lugares diferentes, com versões que não batiam.',
      'Na prática, isso virava pergunta o dia inteiro: em que pé está tal consulta técnica, quem respondeu, o que falta. O controle das consultas técnicas (CTs) era o ponto mais sensível.',
    ],
    modules: [
      { title: 'Consultas Técnicas', text: 'Acompanhamento das CTs com situação, ciclo e responsável. Mostra o que está em aberto há mais tempo e o que parou sem movimento.', shot: '/experience/estel/consultas-tecnicas.png' },
      { title: 'Relatórios de Topografia', text: 'Os relatórios topográficos da obra, com os mesmos filtros e indicadores das CTs.', shot: '/experience/estel/relatorios-topografia.png' },
      { title: 'Equipamentos', text: 'Avanço dos equipamentos por TAG, do registro à assinatura.', shot: '/experience/estel/equipamentos.png' },
      { title: 'Checklist de Montagem', text: 'Fila de checklists por área, tipo e disciplina, com o que falta, o que está pronto e o que acabou de entrar.', shot: '/experience/estel/checklist-montagem.png' },
    ],
    features: ['Busca em todos os módulos', 'Filtros por situação, ciclo, mês e responsável', 'Atualização pela planilha do Drive ou pelo Excel do OneDrive', 'Relatório em PDF e resumo para copiar', 'Funciona no celular, em campo'],
    build: [
      'O código foi escrito inteiramente com IA. A minha parte foi decidir o que o painel precisava resolver: quais controles entrariam, como cada um funcionaria, o que mostrar primeiro e o que deixar de fora.',
      'O painel roda em Google Apps Script, com HTML, CSS e JavaScript, e usa o Google Drive como banco. As planilhas continuam sendo a fonte, e o Drive guarda o histórico de versões.',
    ],
    stack: ['Google Apps Script', 'Google Drive', 'HTML', 'CSS', 'JavaScript', 'Claude'],
    challenge: 'O mais difícil não foi técnico. Foi entender exatamente o que cada pessoa queria ver. São muitas informações, e um painel mal desenhado atrapalha mais do que ajuda.',
    results: [
      { value: '95', label: 'consultas técnicas acompanhadas, 71 já encerradas' },
      { value: '5.895', label: 'itens no checklist de montagem' },
      { value: 'Diário', label: 'uso no controle e nas reuniões, desde julho' },
    ],
    resultsNote: 'Números do painel em setembro de 2026.',
    outcome: 'Além do controle do dia a dia, o painel virou a forma de apresentar a Qualidade nas reuniões e de responder rápido quando alguém precisa de uma informação. Os gerentes viram o uso e me incentivaram a inscrevê-lo no BIS, o programa de inovação da Estel. A apresentação acontece em outubro de 2026.',
  },
  education: [
    { institution: 'Uninter', course: 'Tecnólogo em Análise e Desenvolvimento de Sistemas', period: '2026–atual', status: 'Em andamento', description: 'Graduação em Análise e Desenvolvimento de Sistemas, atualmente em curso.', logo: '/education/uninter-upscaled.png', certificates: [] },
    { institution: 'Human Academy', course: 'Workshops de inteligência artificial e agentes', period: '2026', status: 'Concluído', description: 'Dois workshops sobre agentes de inteligência artificial, com 30 horas de formação concluídas.', logo: '/education/human-mark.svg', certificates: [
      { title: 'Agent Lab', detail: 'Workshop de Agentes · 16h · 2026', image: '/certificates/human-agent-lab.png' },
      { title: 'Agent Lab Build', detail: 'Workshop · 14h · 2026', image: '/certificates/human-agent-lab-build.png' },
    ] },
    { institution: 'Rocketseat', course: 'Fundamentos de desenvolvimento web e Git', period: '2025', status: 'Concluído', description: 'Cursos de programação web e controle de versão com Git e GitHub, com 13 horas concluídas.', logo: '/education/rocketseat-icon.jpg', certificates: [
      { title: 'Discover', detail: 'Programação web · 12h · 2025', image: '/certificates/rocketseat-discover.png' },
      { title: 'O básico de Git e GitHub', detail: 'Controle de versão · 1h · 2025', image: '/certificates/rocketseat-git-github.png' },
    ] },
  ],
  books: [
    { title: 'Steve Jobs', author: 'Walter Isaacson', cover: '/covers/steve.webp' },
    { title: 'Almanack of Naval Ravikant', author: 'Eric Jorgenson', cover: '/covers/naval.webp' },
    { title: 'The Stranger', author: 'Albert Camus', cover: '/covers/stranger.webp' },
    { title: 'Red Rising', author: 'Pierce Brown', cover: '/covers/red rising.webp' },
    { title: 'The Courage to Be Disliked', author: 'Ichiro Kishimi & Fumitake Koga', cover: '/covers/courage.webp' },
    { title: 'Meditations', author: 'Marcus Aurelius', cover: '/covers/meditation.webp' },
    { title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', cover: '/covers/crime and punishment.webp' },
    { title: 'The Rudest Book Ever', author: 'Shwetabh Gangwar', cover: '/covers/rudest book.webp' },
    { title: 'The Old Man and the Sea', author: 'Ernest Hemingway', cover: '/covers/old man and sea (1).webp' },
  ],
  favourites: { movies: ['Interstellar', 'Fight Club', 'The Social Network', 'The Martian', 'The Backrooms', 'Shutter Island'], series: ['Game of Thrones', 'The Boys', 'Silicon Valley', 'Squid Game', 'Breaking Bad'], anime: ['One Piece', 'Naruto', 'Attack on Titan', 'Death Note', 'Vinland Saga', 'Erased'] },
  favouriteDetails: {
    'Interstellar': ['Dir. Christopher Nolan', 'A journey through space and time to save humanity.'],
    'Fight Club': ['Dir. David Fincher', 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club.'],
    'The Social Network': ['Dir. David Fincher', 'The story of the founding of Facebook and the subsequent lawsuits.'],
    'The Martian': ['Dir. Ridley Scott', 'An astronaut becomes stranded on Mars and must rely on his ingenuity to survive.'],
    'The Backrooms': ['Dir. Kane Parsons', 'A young cameraman accidentally falls into a surreal, infinite maze of empty office rooms.'],
    'Shutter Island': ['Dir. Martin Scorsese', 'A U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital.'],
    'Game of Thrones': ['Creators: David Benioff & D.B. Weiss', 'Nine noble families fight for control over the mythical lands of Westeros.'],
    'The Boys': ['Creator: Eric Kripke', 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.'],
    'Silicon Valley': ['Creators: Mike Judge, John Altschuler & Dave Krinsky', 'Follows a group of high-tech startup founders in the Silicon Valley ecosystem.'],
    'Squid Game': ['Creator: Hwang Dong-hyuk', "Hundreds of cash-strapped players accept a strange invitation to compete in children's games."],
    'Breaking Bad': ['Creator: Vince Gilligan', 'A high school chemistry teacher diagnosed with cancer turns to manufacturing meth.'],
    'One Piece': ['Creator: Eiichiro Oda', 'Follows the adventures of Monkey D. Luffy and his pirate crew in search of the ultimate treasure.'],
    'Naruto': ['Creator: Masashi Kishimoto', 'A young ninja seeks recognition from his peers and dreams of becoming the Hokage.'],
    'Attack on Titan': ['Creator: Hajime Isayama', 'After his hometown is destroyed, Eren Jaeger vows to cleanse the earth of the giant humanoid Titans.'],
    'Death Note': ['Creators: Tsugumi Ohba & Takeshi Obata', 'A high school student discovers a supernatural notebook that grants him the ability to kill anyone.'],
    'Vinland Saga': ['Creator: Makoto Yukimura', 'An epic Viking saga detailing vengeance, honor, and the search for a land without war.'],
    'Erased': ['Creator: Kei Sanbe', 'A young manga artist is sent back in time to prevent a kidnapping tragedy from his childhood.'],
  } as Record<string,[string,string]>,

};

export const searchUrl = (title: string) =>
  `https://www.google.com/search?q=${encodeURIComponent(`${title} book`)}`;
